language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-yaap-express' ]; then cd .. && eval "mv $currentfolder generator-yaap-express" && cd generator-yaap-express; fi

